@startuml

class Context{
-Strategy strategy
+doSomething()
}

interface Strategy{
 + doSomething()
}

class ConcreteStrategy1{
 + doSomething()
}
class ConcreteStrategy2{
 + doSomething()
}

Context *-- Strategy
Strategy <|.. ConcreteStrategy1
Strategy <|.. ConcreteStrategy2

@enduml

- 합성관계일 것 같은데.. 답지에는 집약관계
